---
- name: Create directory
  file:
    path: ~/backend
    state: directory

- name: "Copy backend build to server"
  become: yes
  unarchive:
    src:  ~/project/backend.tar.gz
    dest: /home/ubuntu/backend
    creates: /home/ubuntu/backend/src/main.ts
    owner: ubuntu

- name: Install
  become: true
  shell: 
    cd /home/ubuntu/backend
    npm install
    npm run build

- name: start server
  command: pm2 start /home/ubuntu/server/dist/main.js