---
- name: Create directory
  file:
    path: ~/backend
    state: directory

- name: "Copy backend build to server"
  become: yes
  unarchive:
    src:  ~/project/backend.tar.gz
    dest: /home/ubuntu/backend
    creates: /home/ubuntu/backend/dist/main.js
    owner: ubuntu

- name: "copy backend .env file"
  become: true
  copy:
    src: ~/project/backend/.env
    dest: /home/ubuntu/backend/.env

- name: Install
  become: true
  shell: 
    cd /home/ubuntu/backend
    npm install
    npm run build

- name: "Start backend with pm2"
  become: true
  shell: |
    echo "Contents of the .env file (ansible task):"
    cat "~/project/backend/.env"
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm -- start
    #npm run start
    cd dist 
    pm2 start main.js --update-env