---
- name: Move files to server
  become: true
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/app
    
- name: Install
  become: true
  shell: |
    cd /home/ubuntu/app/backend
    npm install
    pm2 stop default
    pm2 start npm -- start